export enum FilterType {
  TEXT = 'TEXT',

  TEXT_IGNORE_CASE_TO_LOWER = 'TEXT_IGNORE_CASE_TO_LOWER',

  TEXT_LIKE = 'TEXT_LIKE',

  DATE = 'DATE',

  DATE_TIME = 'DATE_TIME',

  DATE_TIME_WITH_DATE_PICKER = 'DATE_TIME_WITH_DATE_PICKER',

  SELECT_LIST = 'SELECT_LIST',

  MULTI_SELECT_LIST = 'MULTI_SELECT_LIST',

  BETWEEN = 'BETWEEN',

  CHECKBOX = 'CHECKBOX',

  MODAL_WINDOW = 'MODAL_WINDOW',

  IN = 'IN',
  NUMBER = 'NUMBER',
}
